#!/bin/bash
# =============================================================================
# verify.sh v0.1.0
# =============================================================================
# Purpose:
#   Verifies the integrity of the backup by comparing the current state of the
#   VeraCrypt destination volume against the manifest generated by backup.sh.
#
#   If any files have been added, removed, or changed since the manifest was
#   created, hashdeep will report them and this script will exit non-zero.
#
# Usage:
#   Called by the Flask UI (ui/app.py). Do not run directly unless testing.
#   bash scripts/verify.sh
#
#   NOTE: You must run a backup first (backup.sh) before verify will work.
#         backup.sh generates the manifest that this script checks against.
#
# Dependencies:
#   - python3 + pyyaml (for read_config.py)
#   - hashdeep
#
# Logs:
#   All output is written to logs/backup.log (appended, with timestamps).
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Resolve project root so this works from any working directory.
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_FILE="$PROJECT_ROOT/logs/backup.log"

# -----------------------------------------------------------------------------
# log()
# Writes a timestamped message to both stdout and the log file.
# -----------------------------------------------------------------------------
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Ensure logs directory exists
mkdir -p "$PROJECT_ROOT/logs"

log "========================================================"
log "🧪 Starting verify run"
log "========================================================"

# -----------------------------------------------------------------------------
# Read required config values via the Python helper.
# -----------------------------------------------------------------------------
log "📖 Reading config..."

DEST_DIR=$(python3 "$SCRIPT_DIR/read_config.py" backup.destination_dir)
MANIFEST_FILE=$(python3 "$SCRIPT_DIR/read_config.py" backup.manifest_file)

log "  Destination:    $DEST_DIR"
log "  Manifest file:  $MANIFEST_FILE"

# -----------------------------------------------------------------------------
# Check that the VeraCrypt volume is mounted.
# Verification can't run if the backup destination isn't accessible.
# -----------------------------------------------------------------------------
if ! mountpoint -q "$DEST_DIR"; then
    log "❌ ERROR: VeraCrypt volume is not mounted at $DEST_DIR"
    log "   Please mount your VeraCrypt volume first:"
    log "   sudo veracrypt /dev/sdX $DEST_DIR"
    exit 1
fi
log "✅ VeraCrypt volume confirmed mounted at $DEST_DIR"

# -----------------------------------------------------------------------------
# Check that a manifest exists to verify against.
# The manifest is generated by backup.sh after each successful backup.
# If it doesn't exist, the user needs to run a backup first.
# -----------------------------------------------------------------------------
MANIFEST_PATH="$DEST_DIR/$MANIFEST_FILE"
if [[ ! -f "$MANIFEST_PATH" ]]; then
    log "❌ ERROR: No manifest found at $MANIFEST_PATH"
    log "   Run a backup first — backup.sh generates the manifest."
    exit 1
fi
log "✅ Manifest found: $MANIFEST_PATH"

# -----------------------------------------------------------------------------
# Run hashdeep in audit mode against the manifest.
#
# Flags:
#   -r    recursive (check all files in destination)
#   -a    audit mode: compare current files against the manifest
#   -v    verbose: report on every file checked
#   -f    specify the manifest file to check against
#
# hashdeep exits 0 if everything matches, non-zero if anything differs.
# We capture the exit code and report clearly rather than letting set -e
# kill the script with no explanation.
# -----------------------------------------------------------------------------
log "🔍 Running hashdeep audit against manifest..."
cd "$DEST_DIR"

if hashdeep -r -a -v -f "$MANIFEST_PATH" >> "$LOG_FILE" 2>&1; then
    log "✅ Verification passed — all files match the manifest."
    log "========================================================"
    log "🐀 Verify complete: PASSED"
    log "========================================================"
    exit 0
else
    log "❌ Verification FAILED — files have changed since the last backup."
    log "   Check logs/backup.log for details on which files differ."
    log "========================================================"
    log "🐀 Verify complete: FAILED"
    log "========================================================"
    exit 1
fi
